#!/bin/bash
# Sync CREDENTIALS.md values → .env.dev / .env.staging / .env.prod
# Generated by Phase 3. Run after filling ⏳ placeholders in CREDENTIALS.md.
# Safe to re-run — idempotent. Only writes values that are not still ⏳.

set -euo pipefail
CREDS="CREDENTIALS.md"

if [ ! -f "$CREDS" ]; then
  echo "❌ CREDENTIALS.md not found. Run Bootstrap Step 18 first."
  exit 1
fi

# Count remaining placeholders
pending=$(grep -c "⏳" "$CREDS" || echo 0)
echo "CREDENTIALS.md has $pending unfilled placeholders."

if [ "$pending" -gt 0 ]; then
  echo ""
  echo "Sections still containing ⏳ placeholders:"
  grep -B1 "⏳" "$CREDS" | grep "^##" | sort -u | head -20
  echo ""
  echo "Fill these in CREDENTIALS.md before running Phase 5."
  echo "Proceeding to sync already-filled values..."
fi

# Helper: extract value from CREDENTIALS.md table row by field name
# Usage: extract_value "SMTP Host" → returns the value or "⏳" if unfilled
extract_value() {
  local field="$1"
  grep "^| $field" "$CREDS" 2>/dev/null | head -1 | awk -F'|' '{print $3}' | sed 's/^ *//;s/ *$//' || echo ""
}

# Helper: update .env.{env} with a key=value ONLY if value is not ⏳
# Usage: update_env .env.staging SMTP_HOST "$(extract_value 'SMTP Host')"
update_env() {
  local env_file="$1"
  local key="$2"
  local value="$3"

  [ ! -f "$env_file" ] && return 0
  [[ "$value" == *"⏳"* ]] && return 0  # skip placeholders
  [ -z "$value" ] && return 0            # skip empty

  if grep -q "^${key}=" "$env_file"; then
    # Use | as sed delimiter to avoid clashes with / in URLs/paths
    sed -i "s|^${key}=.*|${key}=${value}|" "$env_file"
    echo "  ✅ $env_file: $key updated"
  else
    echo "${key}=${value}" >> "$env_file"
    echo "  ✅ $env_file: $key appended"
  fi
}

echo ""
echo "─── Syncing SMTP (staging + prod only — dev uses MailHog) ───"
for env in staging prod; do
  update_env ".env.${env}" "SMTP_HOST"      "$(extract_value 'SMTP Host')"
  update_env ".env.${env}" "SMTP_PORT"      "$(extract_value 'SMTP Port')"
  update_env ".env.${env}" "SMTP_USER"      "$(extract_value 'Username')"
  update_env ".env.${env}" "SMTP_PASSWORD"  "$(extract_value 'Password')"
  update_env ".env.${env}" "SMTP_FROM"      "$(extract_value 'From address')"
  update_env ".env.${env}" "SMTP_FROM_NAME" "$(extract_value 'From name')"
done

echo ""
echo "─── Syncing Xendit (if payment.gateway: xendit) ───"
for env in dev; do
  update_env ".env.${env}" "XENDIT_SECRET_KEY"   "$(extract_value 'Secret API Key (TEST)')"
  update_env ".env.${env}" "XENDIT_PUBLIC_KEY"   "$(extract_value 'Public API Key (TEST)')"
  update_env ".env.${env}" "XENDIT_WEBHOOK_TOKEN" "$(extract_value 'Webhook Verification Token')"
done
for env in staging prod; do
  update_env ".env.${env}" "XENDIT_SECRET_KEY"   "$(extract_value 'Secret API Key (LIVE)')"
  update_env ".env.${env}" "XENDIT_PUBLIC_KEY"   "$(extract_value 'Public API Key (LIVE)')"
  update_env ".env.${env}" "XENDIT_WEBHOOK_TOKEN" "$(extract_value 'Webhook Verification Token')"
done

echo ""
echo "─── Syncing Turnstile (prod only — dev/staging use test keys) ───"
update_env ".env.prod" "NEXT_PUBLIC_TURNSTILE_SITE_KEY" "$(extract_value 'Site Key (LIVE)')"
update_env ".env.prod" "TURNSTILE_SECRET_KEY"           "$(extract_value 'Secret Key (LIVE)')"

echo ""
echo "─── Syncing Komodo ───"
for env in staging prod; do
  update_env ".env.${env}" "KOMODO_UI_URL" "$(extract_value 'Komodo UI URL')"
done

echo ""
echo "─── Syncing LiveKit (Yelli core — Third-Party API Keys section) ───"
for env in dev staging prod; do
  update_env ".env.${env}" "LIVEKIT_API_KEY"    "$(extract_value 'LIVEKIT_API_KEY')"
  update_env ".env.${env}" "LIVEKIT_API_SECRET" "$(extract_value 'LIVEKIT_API_SECRET')"
  update_env ".env.${env}" "LIVEKIT_URL"        "$(extract_value 'LIVEKIT_URL')"
done

echo ""
echo "─── Syncing Third-Party API Keys (if any additional rows filled) ───"
# Third-party keys are appended by reading the Third-Party section table rows.
# Humans add their own rows — this loop reads each row and propagates.
awk '/^## 🔑 Third-Party/,/^---$/' "$CREDS" | grep -E "^\| [A-Z_]+" | while IFS='|' read -r _ service key value envs _; do
  key=$(echo "$key" | sed 's/^ *//;s/ *$//')
  value=$(echo "$value" | sed 's/^ *//;s/ *$//')
  envs=$(echo "$envs" | sed 's/^ *//;s/ *$//')

  [[ "$value" == *"⏳"* ]] && continue
  [ -z "$value" ] && continue
  [ -z "$key" ] && continue
  # Skip LiveKit rows — already handled above
  [[ "$key" == LIVEKIT_* ]] && continue

  # "all" → all three env files; else comma-separated list
  if [ "$envs" = "all" ]; then
    target_envs="dev staging prod"
  else
    target_envs=$(echo "$envs" | tr '/' ' ' | tr ',' ' ')
  fi

  for env in $target_envs; do
    update_env ".env.${env}" "$key" "$value"
  done
done

echo ""
echo "✅ Sync complete. Run 'pnpm tools:check-env' to verify env files pass validation."
echo "   If CREDENTIALS.md still has ⏳ placeholders, Phase 5 pre-flight will list them."
